handle: mollie
isFrontendEnabled: '1'
name: mollie
orderCondition:
  class: craft\commerce\elements\conditions\orders\GatewayOrderCondition
  elementType: craft\commerce\elements\Order
  fieldContext: global
paymentType: authorize
settings:
  apiKey: $MOLLIE_API_KEY
  carrier: ''
  completeBanktransferOrders: false
  profileId: $VITE_MOLLIE_PROFILE_ID
  sendCartInfo: true
  testMode: '0'
  trackAndTrace: ''
  trackingEnabled: false
  trackingUrl: ''
sortOrder: 99
type: white\commerce\mollie\plus\gateways\Gateway
