defaultPlacement: end
descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: accessories
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
isStructure: false
maxLevels: null
maxVariants: null
name: Accessories
productFieldLayouts:
  134fc43a-d653-497c-9ab7-19bdef01b004:
    cardThumbAlignment: end
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-06T12:03:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 34fe7087-0cb5-4c06-a32a-aa34ee763d77
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2025-08-06T12:03:22+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 890af33b-948a-4f41-991a-cea6c490f1fe
            userCondition: null
            warning: null
        name: Content
        uid: 11a9e18a-6244-42bb-92e4-a72988e47af4
        userCondition: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
propagationMethod: all
siteSettings:
  f3f391fe-c122-4353-8066-f4933e71a5bb: # A4-Madam-LodeSnaet
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'accessories/{slug}'
skuFormat: ''
variantFieldLayouts:
  f19ff345-20fa-4c3e-93ee-f8655cfb58fa:
    cardThumbAlignment: end
    cardView:
      - sku
      - priceView
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-06T12:03:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: d104f404-0eaa-494f-9ed8-9a3308ce1df5
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2025-08-06T12:03:22+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: 20d62b48-25b8-4585-9779-11f87b17023a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2025-08-06T12:03:22+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: ce83340e-8ae6-487a-b767-d396f3220dfe
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2025-08-06T12:03:22+00:00'
            defaultAllowOutOfStockPurchases: false
            defaultInventoryTracked: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 8bbfdc14-e29a-4bd0-8920-9d989ab4bc17
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2025-08-06T12:03:22+00:00'
            defaultAvailableForPurchase: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: 07055a61-f38b-4dc3-a71b-b1636f808849
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2025-08-06T12:03:22+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 94ec835f-162b-4674-b282-5e9927b2707f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2025-08-06T12:03:22+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: df1ef4ff-862a-476e-a31f-89dfb4fc26be
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2025-08-06T12:03:22+00:00'
            defaultPromotable: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: 530bf258-3cb9-45ec-8c95-c88c6310a064
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2025-08-06T12:03:22+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 5e173efa-b0fd-47c7-a809-eede9d3d8c3a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2025-08-06T12:03:22+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: 0fcc1b1b-36ed-4784-ba0c-6cfb77b5eb31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f7510869-3ca9-4b8f-af64-49d9f7869694
        userCondition: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
