color: green
description: null
fieldLayouts:
  b00c206a-85f5-48ff-90ff-330f01af2f71:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-06T13:49:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c19e6031-187f-4488-aaf1-e118ca3411d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2ecc22d9-2d71-4085-a188-675658d07ea7
        userCondition: null
handle: brand
hasTitleField: true
icon: copyright
name: Brand
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
