color: blue
description: null
fieldLayouts:
  783cde28-d5c0-493e-ba16-7a5eed9284f9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-03T09:22:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 97b26ae8-2eae-45a7-ace3-6e902a344d98
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-03T09:26:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f060edf-62d8-4220-85b4-3b1f8aa69b12 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44d26c99-3d60-4e37-8421-efcdfb0e815e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-03T09:26:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c842f534-2b53-4157-b4ee-b83d5368e32a # Email address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7f72c10-ed47-4261-a1e8-02017cc35d83
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-03T12:31:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c5a126f7-6e3d-4031-9d6b-74ef38546d5c # cart
            handle: email
            includeInCards: false
            instructions: null
            label: email
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 852e35d1-9d0c-4c9e-bef9-072eba0cbcbb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a3e7bcc-d863-4ad8-9e02-cee6812fdbe3
        userCondition: null
handle: email
hasTitleField: true
icon: at
name: Email
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
