color: green
description: null
fieldLayouts:
  f975e0d1-ecb1-4d93-8178-7f6017c4bfc0:
    cardThumbAlignment: end
    tabs:
      - elementCondition: null
        elements:
          - autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-09T12:44:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd7b248e-87d8-46e0-a33b-4d251e0e8884
            userCondition: null
            warning: null
            width: 100
          - dateAdded: '2025-07-31T10:25:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2d2f39e1-6a53-4a47-a1be-f3915352a25e # New Section
            handle: _sections
            includeInCards: false
            instructions: null
            label: Sections
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f64ee363-0aec-40e1-a7ca-5e97b37ec0b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a4cefe93-0049-497d-9a37-29137a909d46
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
