color: orange
description: null
fieldLayouts:
  3227b70d-7d63-4675-aa9a-3ef39cbdccba:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-31T09:52:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: "To emphasize the first part of a title in italics, place a # immediately after the part you want italicized.\r\nExample: Defilé at# Waregem Koerse → Defilé at Waregem Koerse"
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b79cbb7e-2183-40a3-8248-65a1887dbfb5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-31T13:03:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a591d79-2f21-4016-8693-6d659f337a0e # Featured Products
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48fc6ebd-08a1-4022-ad56-c100ddf452bf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9af7f70a-e8d5-4a42-b237-b61ea465365e
        userCondition: null
handle: newProducts
hasTitleField: true
icon: product-hunt
name: 'New Products'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
