color: blue
description: null
fieldLayouts:
  c0609621-573a-4da5-988b-4cf864fcc635:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-04T12:07:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5f8cfd88-460f-4387-b1d1-c4c7408c39a9 # Blog Link
            handle: socialLink
            includeInCards: false
            instructions: null
            label: 'Social Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ada11b1f-2397-4004-a653-23d28f938ec7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 726dc1e2-fb73-4573-bc2f-e11f15b8abf3
        userCondition: null
handle: socalLinks
hasTitleField: false
icon: computer-mouse-scrollwheel
name: 'Socal Links'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
