defaultPlacement: end
fieldLayouts:
  a833130c-033c-43ca-83d6-bc7b08fc0bb6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-07T12:26:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 26f3f43c-f21d-4f7e-986a-df9f5b8f5ede
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-10T19:58:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a1aeea18-853e-493d-9338-42e58ca3ae51 # Min
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bf5d503-3375-4e46-adcc-7c48d0798c2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-10T19:58:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a1aeea18-853e-493d-9338-42e58ca3ae51 # Min
            handle: max
            includeInCards: false
            instructions: null
            label: Max
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19620570-ae4b-457f-9c86-97ea34a34b0a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5492328e-481c-4099-bed4-d2bcc734936a
        userCondition: null
handle: price
name: Price
siteSettings:
  f3f391fe-c122-4353-8066-f4933e71a5bb: # A4-Madam-LodeSnaet
    hasUrls: true
    template: price/_category.twig
    uriFormat: 'shop?=price{slug}'
structure:
  maxLevels: null
  uid: 4cdfeef6-e8e0-4adf-815b-eaa818bb2df3
