baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: nl-BE
name: A4-Madam-LodeSnaet
primary: true
siteGroup: c7613314-594d-4ecd-9e3b-11245f68ded9 # A4-Madam-LodeSnaet
sortOrder: 1
