altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  769dc854-af31-4e6f-be42-35db40ca472f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-10T17:51:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1cec9ebc-e8d7-41a9-b3bd-1e4fc4671987
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 711a5f89-0fc1-4aa9-8c78-af9c5e5f0d81
        userCondition: null
fs: hero
handle: hero
name: Hero
sortOrder: 6
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
