altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  39982dc4-d9af-434f-a8c7-66aa7db54032:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-30T15:51:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 58dd7da0-6225-4d8b-ac63-9dcff7decc42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c555cdc2-e6c8-4138-a6bb-c014ff5847ab
        userCondition: null
fs: logos
handle: logos
name: Logos
sortOrder: 3
subpath: logos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
