columnSuffix: null
handle: companyAddress
instructions: null
name: 'Company Address'
searchable: false
settings:
  maxAddresses: 1
  minAddresses: 1
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
