columnSuffix: null
handle: featuredProducts
instructions: null
name: 'Featured Products'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 4
  minRelations: null
  selectionLabel: null
  showCardsInGrid: true
  showSearchInput: true
  showSiteMenu: true
  sources:
    - 'productType:5f6fd9c7-7171-4031-a9b1-e79782bbf63e' # Handbags
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\commerce\fields\Products
