columnSuffix: null
handle: newestProducts
instructions: null
name: 'Newest Products'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
