columnSuffix: null
handle: openingHours
instructions: null
name: 'Opening Hours'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
