columnSuffix: null
handle: priceRange
instructions: null
name: 'Price Range'
searchable: false
settings:
  defaultValue: null
  max: 100
  min: 0
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
