columnSuffix: null
handle: style
instructions: null
name: Style
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Solid
        -
          - value
          - solid
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Regular
        -
          - value
          - regular
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Light
        -
          - value
          - light
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
