dateModified: 1752143832
email:
  fromEmail: lode.snaet@student.howest.be
  fromName: A4-Madam-LodeSnaet
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDiskImages:
    hasUrls: true
    name: 'Hard Disk images'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    0a591d79-2f21-4016-8693-6d659f337a0e: Products # Products
    0a7147ff-00d0-400d-b9c6-a5b60295b4cb: img-webp # img-webp
    3dffe27e-54da-47fc-91bc-346060a36dda: Navigation # Navigation
    5f6fd9c7-7171-4031-a9b1-e79782bbf63e: Handbags # Handbags
    6e36b952-2450-4694-be45-3489d7c759f3: Table # Table
    7f060edf-62d8-4220-85b4-3b1f8aa69b12: Description # Description
    8b62c7dd-2811-43a9-b770-a9f0a3e09a4e: 'Product photos' # Product photos
    12f0a5a8-dcff-4e9d-9bc4-839628f6a7a1: New # New
    84cbb83b-f415-4a70-a2f8-02cbe755fd8d: 'Public Schema' # Public Schema
    89c6e739-006e-415e-88bc-052190cddb2e: Category # Category
    761a01d0-8414-40af-8d2b-2d4edde3401d: Dummy # Dummy
    43597ccb-dafa-4c5a-bcc5-5a0017246efb: 'Product Photos' # Product Photos
    978520f0-e790-46cd-9e23-7f09141d0fbd: Home # Home
    90004640-0fe5-425e-8935-922d75d8d641: Home # Home
    a2de9583-bb44-457e-92aa-e6f71bbf82a3: Price # Price
    af8aef47-fb82-491f-a835-363b8f5d8995: Products # Products
    b871443b-88e1-47c1-9fff-4ada87e917ac: Primary # Primary
    bfd784b9-b276-406b-89cf-539b1d8f6750: 'Gift Vouchers' # Gift Vouchers
    c7613314-594d-4ecd-9e3b-11245f68ded9: A4-Madam-LodeSnaet # A4-Madam-LodeSnaet
    cfb54b6d-ea39-4fc1-a0e5-78fe5893ab9c: Header # Header
    f3f391fe-c122-4353-8066-f4933e71a5bb: A4-Madam-LodeSnaet # A4-Madam-LodeSnaet
    f242d7ff-1193-43e1-98e2-3e023bc89293: Filters # Filters
    f585ace5-a912-453c-8942-d37f1044937e: Shop # Shop
plugins:
  commerce:
    edition: pro
    enabled: true
    licenseKey: UHL4RLJJTV9Z2L9I3LBDNRBU
    schemaVersion: 5.4.0.4
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 1SQTEQOIB9Y7EULLXF31FWTA
    schemaVersion: 3.0.13
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: A4-Madam-LodeSnaet
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
