dateModified: 1754834107
elementSources:
  craft\commerce\elements\Order:
    -
      key: '*'
      type: native
    -
      heading: Primary
      key: 'heading:fafd9648-e4d0-41e1-9d2b-3ee8352cab7e'
      type: heading
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: cards
      disabled: false
      key: 'carts:active:primary'
      tableAttributes:
        - shortNumber
        - dateUpdated
        - totalPrice
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: cards
      disabled: false
      key: 'carts:inactive:primary'
      tableAttributes:
        - shortNumber
        - dateUpdated
        - totalPrice
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: cards
      disabled: false
      key: 'carts:attempted-payment:primary'
      tableAttributes:
        - shortNumber
        - dateUpdated
        - totalPrice
      type: native
  craft\elements\Category:
    -
      key: 'group:48979a7b-9e8c-4be7-b24f-4714635f81d7' # Collection
      type: native
    -
      key: 'group:879c3a0a-5b69-4238-8ac9-c538fb3f6441' # Style
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'group:c511b290-68a9-43f6-970b-1cd171e7da3c' # Price
      tableAttributes:
        - status
        - link
      type: native
    -
      key: 'group:72640ef2-14a8-4b85-94d8-b700005825f8' # Colour
      type: native
    -
      key: 'group:bc2e621d-fb6d-4105-8932-a9c64ed14981' # Material
      type: native
    -
      key: 'group:3a90dbe2-25db-42a9-9c5b-600c36793485' # Condition
      type: native
email:
  fromEmail: lode.snaet@student.howest.be
  fromName: A4-Madam-LodeSnaet
  replyToEmail: lode.snaet@outlook.com
  template: _email/sendemail.twig
  transportSettings:
    host: $SERVD_SMTP_HOSTNAME
    password: $SERVD_SMTP_PASSWORD
    port: $SERVD_SMTP_PORT
    useAuthentication: '1'
    username: $SERVD_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  blogPhotos:
    hasUrls: false
    name: 'Blog Photos'
    settings:
      cdnUrlPattern: ''
      customSubfolder: /blogphotos
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/blogphotos/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://lodesnaet-madam.files.svdcdn.com'
  featuredCollection:
    hasUrls: false
    name: 'Featured Collection'
    settings:
      cdnUrlPattern: ''
      customSubfolder: /featuredcollection
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/featuredcollection/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://lodesnaet-madam.files.svdcdn.com'
  logos:
    hasUrls: false
    name: Logos
    settings:
      cdnUrlPattern: ''
      customSubfolder: /logos
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/logos/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://lodesnaet-madam.files.svdcdn.com'
  productPhotos:
    hasUrls: false
    name: 'Product Photos'
    settings:
      cdnUrlPattern: ''
      customSubfolder: /productphotos
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/productphotos/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://lodesnaet-madam.files.svdcdn.com'
  reviewPhotos:
    hasUrls: false
    name: 'Review Photos'
    settings:
      cdnUrlPattern: ''
      customSubfolder: /reviewphotos
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/reviewphotos/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://lodesnaet-madam.files.svdcdn.com'
meta:
  __names__:
    0a591d79-2f21-4016-8693-6d659f337a0e: 'Featured Products' # Featured Products
    0a7147ff-00d0-400d-b9c6-a5b60295b4cb: img2webp # img2webp
    0db05413-f161-4551-8a65-e6a1599a263b: 'Review Photos' # Review Photos
    1ea0b14a-de19-4214-8c42-7ed67e65b61b: Logo # Logo
    2b21e46c-e073-45a6-95ba-60da477afb35: 'Price Range' # Price Range
    2d2f39e1-6a53-4a47-a1be-f3915352a25e: 'New Section' # New Section
    3a90dbe2-25db-42a9-9c5b-600c36793485: Condition # Condition
    3c2a8ec8-0af0-410c-8825-09cc1334b3a6: Featured # Featured
    3ca35d9d-5957-47ac-a9bd-9b7b7f9c0b0b: Category # Category
    3e445162-97ee-4a6b-9316-0f3b3369de05: 'Newest Products?' # Newest Products?
    5a2ef762-9572-4b86-8dc4-96b99a63e0a5: Footer # Footer
    5f6fd9c7-7171-4031-a9b1-e79782bbf63e: Handbags # Handbags
    5f8cfd88-460f-4387-b1d1-c4c7408c39a9: 'Blog Link' # Blog Link
    6e36b952-2450-4694-be45-3489d7c759f3: Table # Table
    6e83d1f0-b6e7-42b9-9aeb-a51cd5a89e9c: Size # Size
    7bcdad0b-765b-4f33-9acd-73631a767a59: Certificate # Certificate
    7f060edf-62d8-4220-85b4-3b1f8aa69b12: Description # Description
    8a6cc43c-2409-4184-9196-b5974f34bf2b: Material # Material
    8ab333ec-a77f-4c59-bc0d-cd6b83a0d18a: Condition # Condition
    8b62c7dd-2811-43a9-b770-a9f0a3e09a4e: 'Product photos' # Product photos
    9da5f1f2-8d0e-45c2-a2f7-17cdd3aa4d76: 'Review Photos' # Review Photos
    11c7d1dd-b301-4ef7-9811-366860cf882f: Breadcrumbs # Breadcrumbs
    12f0a5a8-dcff-4e9d-9bc4-839628f6a7a1: New # New
    21a28ead-39b2-4dcc-8b62-01bbb71c4d10: Colour # Colour
    76f15ab4-3e47-44e3-9590-6013840d9609: 'Featured Collection' # Featured Collection
    80ac1637-5252-4d1d-930b-014aefc841e9: 'Opening Hours' # Opening Hours
    84cbb83b-f415-4a70-a2f8-02cbe755fd8d: 'Public Schema' # Public Schema
    89c6e739-006e-415e-88bc-052190cddb2e: Category # Category
    392c0803-5557-414c-9823-6a92be5b3ab6: Blog # Blog
    454dd17b-a65a-4bc6-82ce-c844cb73823a: 'Product Detail' # Product Detail
    761a01d0-8414-40af-8d2b-2d4edde3401d: Dummy # Dummy
    879c3a0a-5b69-4238-8ac9-c538fb3f6441: Style # Style
    880e5a63-3f9c-49c5-b677-7cc7002b9509: 'Company Address' # Company Address
    934ce298-c047-4f35-ad67-2ac598065d77: 'Company Info' # Company Info
    956a9245-46dc-4883-bec5-6e4750d386e9: Brand # Brand
    3629a7bb-4313-44bc-b6a8-483d582aa6c7: Review # Review
    4569f930-a5e2-48d1-bf7f-fe087b362050: 'Order By Value' # Order By Value
    9305b33c-0caf-4986-ad17-86f8114e6de0: Socials # Socials
    32956aab-afca-40f2-99a9-2619b9a4f7b7: 'Blog Photos' # Blog Photos
    43597ccb-dafa-4c5a-bcc5-5a0017246efb: 'Product Photos' # Product Photos
    48979a7b-9e8c-4be7-b24f-4714635f81d7: Collection # Collection
    72640ef2-14a8-4b85-94d8-b700005825f8: Colour # Colour
    838954d2-4ef6-4c09-8fe2-0203b415b633: Style # Style
    978520f0-e790-46cd-9e23-7f09141d0fbd: Home # Home
    6516610b-24f3-4763-840c-c7115929cf6d: Accessories # Accessories
    90004640-0fe5-425e-8935-922d75d8d641: Home # Home
    a2de9583-bb44-457e-92aa-e6f71bbf82a3: Price # Price
    a23d853b-6c0b-47a9-aceb-b20f36068340: Email # Email
    a97ece80-d59b-4ecb-af02-d9dee54b22a8: 'Blog posts' # Blog posts
    af8aef47-fb82-491f-a835-363b8f5d8995: Products # Products
    b370be02-0547-4865-bce1-32500f619a6c: 'Socal Links' # Socal Links
    b871443b-88e1-47c1-9fff-4ada87e917ac: Primary # Primary
    bc2e621d-fb6d-4105-8932-a9c64ed14981: Material # Material
    bfd784b9-b276-406b-89cf-539b1d8f6750: 'Gift Vouchers' # Gift Vouchers
    c5a126f7-6e3d-4031-9d6b-74ef38546d5c: cart # cart
    c511b290-68a9-43f6-970b-1cd171e7da3c: Price # Price
    c842f534-2b53-4157-b4ee-b83d5368e32a: 'Email address' # Email address
    c4932be2-4962-4751-bf3e-0894a3ea6799: Logos # Logos
    c7613314-594d-4ecd-9e3b-11245f68ded9: A4-Madam-LodeSnaet # A4-Madam-LodeSnaet
    cffb2338-4ca7-451b-b20a-72f01860e7f1: mollie # mollie
    d25a7f51-e4af-4763-baae-3e8889bfb788: Copyright # Copyright
    dbeafd55-e635-450d-80d3-83a7539a5e6e: 'Menu Layout' # Menu Layout
    ef00bb55-1f00-4476-982b-9c10e664b8aa: 'Phone Number' # Phone Number
    ef50746b-64cf-4839-9692-66daec250d96: Navbar # Navbar
    f0399099-c3dd-4522-a280-b436ff29345a: sections # sections
    f3f391fe-c122-4353-8066-f4933e71a5bb: A4-Madam-LodeSnaet # A4-Madam-LodeSnaet
    f9ff1ecb-2804-4771-96af-331574c00970: 'Legal Links' # Legal Links
    f31dd96b-308e-4557-8ab1-e45693fd7d0f: 'Featured Collection' # Featured Collection
    f93ce853-d6ae-4caa-8b25-a019801c6cea: 'New Products' # New Products
    f242d7ff-1193-43e1-98e2-3e023bc89293: Filters # Filters
    f585ace5-a912-453c-8942-d37f1044937e: Shop # Shop
    fcc24a04-69b5-4437-b473-3fb2d2fd38a7: Collection # Collection
plugins:
  commerce:
    edition: pro
    enabled: true
    licenseKey: UHL4RLJJTV9Z2L9I3LBDNRBU
    schemaVersion: 5.4.0.5
    settings:
      activeCartDuration: 3600
      cartVariable: cart
      defaultView: commerce/products
      dimensionUnits: mm
      gatewayPostRedirectTemplate: ''
      loadCartRedirectUrl: null
      paymentCurrency: null
      pdfAllowRemoteImages: false
      purgeInactiveCarts: true
      purgeInactiveCartsDuration: 7776000
      updateBillingDetailsUrl: ''
      updateCartSearchIndexes: true
      validateCartCustomFieldsOnSubmission: false
      weightUnits: g
  commerce-mollie:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  icon-picker:
    edition: standard
    enabled: true
    licenseKey: TR2PMUNKV8186RP524XLXHGR
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 1SQTEQOIB9Y7EULLXF31FWTA
    schemaVersion: 3.0.13
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: '1'
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      clearCdnCacheWhenAssetChanges: '1'
      disableDynamic: ''
      disableTransforms: ''
      fsMaps:
        __assoc__:
          -
            - blogPhotos
            - none
          -
            - logos
            - none
          -
            - productPhotos
            - none
          -
            - reviewPhotos
            - none
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: ''
      projectSlug: ''
      securityKey: ''
      suppressWarnings: ''
      transformSvgs: 'no'
      useLocalVolumes: false
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: A4-Madam-LodeSnaet
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: Europe/Amsterdam
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
