fieldLayouts:
  727a3259-64c8-41a6-a76d-558ca7026890:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-04T10:23:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6e36b952-2450-4694-be45-3489d7c759f3 # Table
            handle: menuLinks
            includeInCards: false
            instructions: null
            label: 'Menu Links'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bcd06e2-9668-4042-9b74-9c14dbca68a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-11T14:29:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dbeafd55-e635-450d-80d3-83a7539a5e6e # Menu Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb4d475d-b8be-4ce1-a908-0a8ae5cd2d96
            userCondition: null
            warning: null
            width: 100
        name: Menu
        uid: e90751ea-00e5-48fd-a5fe-1af454857696
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
