fieldLayouts:
  9dbaf97f-7e4e-438e-aa4b-2b476f43d7c7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-09T18:08:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6e36b952-2450-4694-be45-3489d7c759f3 # Table
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 811a57e3-a5c2-4fd8-9a31-272d521ecbb6
            userCondition: null
            warning: null
            width: 100
        name: Menu
        uid: 622b9ac8-1249-4190-95a7-4c4ec5cca99f
        userCondition: null
handle: navigation
name: Navigation
sortOrder: 1
