defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 956a9245-46dc-4883-bec5-6e4750d386e9 # Brand
handle: collections
maxAuthors: 1
name: Collections
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f3f391fe-c122-4353-8066-f4933e71a5bb: # A4-Madam-LodeSnaet
    enabledByDefault: true
    hasUrls: true
    template: collections/_entry.twig
    uriFormat: 'collections/{slug}'
structure:
  maxLevels: null
  uid: 62a4963e-25ff-429e-ad53-eba88f75e7b5
type: structure
