defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 978520f0-e790-46cd-9e23-7f09141d0fbd # Home
  -
    uid: b3334983-e3a4-4def-b5d5-0458cf5727f0 # Post
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f3f391fe-c122-4353-8066-f4933e71a5bb: # A4-Madam-LodeSnaet
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
