defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f0399099-c3dd-4522-a280-b436ff29345a # sections
handle: productDetail
maxAuthors: 1
name: 'Product Detail'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - shop/christian-dior-lady-dior-in-patent-leather-with-silver-hardware
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f3f391fe-c122-4353-8066-f4933e71a5bb: # A4-Madam-LodeSnaet
    enabledByDefault: true
    hasUrls: true
    template: _shop/_product.twig
    uriFormat: 'shop/{slug}'
type: single
