defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f242d7ff-1193-43e1-98e2-3e023bc89293 # Filters
  -
    uid: 89c6e739-006e-415e-88bc-052190cddb2e # Category
  -
    uid: af8aef47-fb82-491f-a835-363b8f5d8995 # Products
handle: shop
maxAuthors: 1
name: Shop
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f3f391fe-c122-4353-8066-f4933e71a5bb: # A4-Madam-LodeSnaet
    enabledByDefault: true
    hasUrls: true
    template: _shop/index.twig
    uriFormat: shop
type: single
